name: dividing two numbers 
description: using mode operation
inputs:
      first_number:
        required: true
        type: number
      second_number:
        required: true 
        type: number


runs:
   
    using: "composite"
    steps:
      - name: divide two number
        run: | 
              if [[ "${{ inputs.first_number }}" =~ ^[0-9]+$ && "${{ inputs.second_number }}" =~ ^[0-9]+$ ]];then
              if [[ "${{ inputs.second_number }}" || "${{ inputs.first_number }}" != "0" ]]; then
              
              if [[ $(( ${{ inputs.first_number }} % ${{ inputs.second_number }} )) -eq 0 ]]; 
              then
               echo "number is completely divisible"
              else 
               echo "it is not completely divisible" 
              fi
              else
               echo  "please add another number rather than zero"
              fi
              else
               echo "please enter positive integer value "
              fi

        shell: bash  
#result=$(curl -s GET -- header "Accept:*/*" "https://api.github.com/users/{GH_USERNAME}") 
 # echo $result

 #curl -L \
            #-H "Accept: application/vnd.github+json" \
            #-H "Authorization: Bearer <YOUR-TOKEN>" \
            #-H "X-GitHub-Api-Version: 2022-11-28" \
            # https://api.github.com/users 

 #curl -L \
   #-H "Accept: application/vnd.github+json" \
   #-H "Authorization: Bearer ${{ env.pat_token }}" \
   #-H "X-GitHub-Api-Version: 2022-11-28" \
   #https://api.github.com/users{GH_USERNAME} 

      #curl --request GET \
      #--url "https://docs.github.com/rest/users/GH_USERNAME" \
      #--header "Accept: application/vnd.github+json" \
      #--header "Authorization: Bearer $GH_TOKEN"  
      
                 
      # curl "https://api.github.com/users/$GH_USERNAME/repos?per_page=100" | grep -o 'git@[^"]*'
          # curl "https://api.github.com/users/$GH_USERNAME/events/public"


          #name: Validate GitHub Username

#on:
  #push:
    #branches:
      #- main

#jobs:
  #validate_username:
    #runs-on: ubuntu-latest

    #steps:
      #- name: Check GitHub Username
        #id: check_username
        #run: |
          #USERNAME="${{ inputs.Username }}"
          #GITHUB_API="https://api.github.com/users/${{ inputs.Username }}"

          # Regular expression to check if the username contains only alphanumeric characters or hyphens
          #if ! [[ $USERNAME =~ ^[a-zA-Z0-9-]{1,39}$ ]]; then
           # echo "Invalid GitHub username: $USERNAME (contains special characters or exceeds 39 characters)"
           # exit 1
          #fi

          #response=$(curl -s -o /dev/null -w "%{http_code}" "$GITHUB_API")

          #if [[ $response -eq 200 ]]; then
            #curl -L \
              #-H "Accept: application/vnd.github+json" \
              #H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
              #-H "X-GitHub-Api-Version: 2022-11-28" \
              #"https://api.github.com/users/${{ inputs.Username }}"
          #else
            #echo "Invalid GitHub username: $USERNAME"
          #fi

        #env:
          #PAT_TOKEN: ${{ secrets.GITHUB_PAT }}
