name: dividing two numbers 
description: using mode operation
inputs:
      first_number:
        required: true
        type: number
      second_number:
        required: true 
        type: number


runs:
   
    using: "composite"
    steps:
      - name: divide two number
        run: | 
              if [[ "${{ inputs.first_number }}" =~ ^[0-9]+$ && "${{ inputs.second_number }}" =~ ^[0-9]+$ ]];then
              if [[ "${{inputs.second_number}}" != "0" ]]; then
              if [ $(( ${{ inputs.first_number }} % ${{ inputs.second_number }} )) -eq 0 ]; 
              then
               echo "number is completely divisible"
              else 
               echo "it is not completely divisible" 
              fi
              else
               echo please add another number rather than zero
              fi
              else
               echo "please enter numeric value "
              fi

        shell: bash  
