name: dividing two numbers 
description: using mode operation
inputs:
      first_number:
        required: true
        type: number
      second_number:
        required: true 
        type: number
runs:
    using: "composite"
    steps:
    - name: Dividing two values
      run: |
            if [ $(( ${{inputs.first_number}} % ${{inputs.second_number}} )) -eq 0 ] && [$((grep -E '^[0-9]+$')) ]; 
            then
             echo "number is completely divisible"
            else 
             echo "it is not completely divisible" 
            fi
      shell: bash  
