name: dividing two numbers 
description: using mode operation
inputs:
      first_number:
        required: true
        type: string
      second_number:
        required: true 
        type: string


runs:
   
    using: "composite"
    steps:
      run: | 
            if [[ "${{ inputs.first_number }}" =~ ^[0-9]+$ && "${{ inputs.second_number }}" =~ ^[1-9]+$ ]];then
            if [ $(( ${{ inputs.first_number }} % ${{ inputs.second_number }} )) -eq 0 ]; 
            then
             echo "number is completely divisible"
            else 
             echo "it is not completely divisible" 
            fi
            else
             echo "please enter numeric value "
            fi
            
      shell: bash  
